spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/testkeycloak}
      auto-index-creation: ${MONGO_AUTO_INDEX:true}
  application:
    name: ${APP_NAME:user-service}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:keycloak}
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: ${SERVER_PORT:8081}

# Application Configuration
app:
  frontend-url: ${FRONTEND_URL:http://localhost:8081}
  email-verification-url: ${EMAIL_VERIFICATION_URL:http://localhost:8081/auth/verify-email}

# Mailjet Configuration
mailjet:
  api:
    key: ${MAILJET_API_KEY:your-mailjet-api-key}
    secret: ${MAILJET_API_SECRET:your-mailjet-api-secret}
  from:
    email: ${MAILJET_FROM_EMAIL:noreply@example.com}
    name: ${MAILJET_FROM_NAME:Your App Name}

---
# Keycloak Profile (default for UI login)
spring:
  config:
    activate:
      on-profile: keycloak
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:spring-boot-app}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/spring-boot-realm}
            user-name-attribute: preferred_username

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:spring-boot-realm}
  resource: ${KEYCLOAK_CLIENT_ID:spring-boot-app}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}

---
# Development Profile (without OAuth2)
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration: {}
        provider: {}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:spring-boot-realm}
  resource: ${KEYCLOAK_CLIENT_ID:spring-boot-app}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
